<#
.SYNOPSIS
    Regenerates .gitattributes with one Git LFS rule per file at or above the threshold.
    Default threshold is 100 MB (GitHub's hard push limit).

.DESCRIPTION
    Walks the repository, finds large files, writes a sorted .gitattributes that LFS-tracks each by its repository-relative path.
    Make sure to run before `git add` so the files actually go through the LFS filter on stage.
    The .gitattributes file is overwritten in full on every run.

.PARAMETER RepositoryRoot
    Repository root to scan. Defaults to the parent of this script's folder.

.PARAMETER FileSizeThreshold
    File size threshold. Default: 100MB.

.EXAMPLE
    .\generate-git-attributes.ps1
    .\generate-git-attributes.ps1 -FileSizeThreshold 50MB
#>
[CmdletBinding()]
param(
    [string] $RepositoryRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).ProviderPath,
    [long]   $FileSizeThreshold = 100MB
)

$ErrorActionPreference = 'Stop'

$attrFile = Join-Path $RepositoryRoot '.gitattributes'
$sep      = [IO.Path]::DirectorySeparatorChar

$patterns = Get-ChildItem -LiteralPath $RepositoryRoot -File -Recurse -Force -ErrorAction SilentlyContinue |
    Where-Object { $_.Length -ge $FileSizeThreshold -and ($_.FullName.Split($sep) -notcontains '.git') } |
    ForEach-Object {
        $rel = $_.FullName.Substring($RepositoryRoot.Length).TrimStart($sep) -replace '\\', '/'
        if ($rel -match '\s') { '"{0}"' -f $rel } else { $rel }
    } |
    Sort-Object

$header = @(
    '# Auto-Generated By "scripts/generate-git-attributes.ps1"'
    '# Re-Generate After Adding New Large Files'
    ''
    "# Generated: $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))"
    "# Threshold: $([math]::Round($FileSizeThreshold / 1MB, 0)) MB"
    ''
)
$rules   = $patterns | ForEach-Object { "$_ filter=lfs diff=lfs merge=lfs -text" }
$content = (($header + $rules) -join "`n") + "`n"

[IO.File]::WriteAllText($attrFile, $content, [Text.UTF8Encoding]::new($false))

Write-Host ("{0} File(s) Flagged | Wrote {1}" -f $patterns.Count, $attrFile)
