<#
.SYNOPSIS
    Regenerates .gitattributes with one Git LFS rule per file at or above the threshold.
    Default threshold is 100 MB (GitHub's hard push limit).
    Files whose extension is in $AlwaysLFSExtensions are also LFS-tracked, regardless of size.

.DESCRIPTION
    Walks the repository, finds matching files, writes a grouped .gitattributes that LFS-tracks each by its repository-relative path.
    Output is grouped: one section per always-LFS extension (in the order given), then a final section for files at or above the size threshold that don't match any extension. Sections are separated by a blank line; empty groups are skipped.
    Make sure to run before `git add` so the files actually go through the LFS filter on stage.
    The .gitattributes file is overwritten in full on every run.

.PARAMETER RepositoryRoot
    Repository root to scan. Defaults to the parent of this script's folder.

.PARAMETER FileSizeThreshold
    File size threshold. Default: 100MB.

.PARAMETER AlwaysLFSExtensions
    Extensions (with or without leading dot) to LFS-track regardless of size. Default: '.s2z'.

.EXAMPLE
    .\generate-git-attributes.ps1
    .\generate-git-attributes.ps1 -FileSizeThreshold 50MB
    .\generate-git-attributes.ps1 -AlwaysLFSExtensions '.s2z','.dll'
#>
[CmdletBinding()]
param(
    [string]   $RepositoryRoot      = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).ProviderPath,
    [long]     $FileSizeThreshold   = 100MB,
    [string[]] $AlwaysLFSExtensions = @('.s2z')
)

$ErrorActionPreference = 'Stop'

$attrFile = Join-Path $RepositoryRoot '.gitattributes'
$sep      = [IO.Path]::DirectorySeparatorChar

$alwaysLFS = $AlwaysLFSExtensions |
    ForEach-Object { if ($_.StartsWith('.')) { $_ } else { '.' + $_ } } |
    Sort-Object -Unique

$extGroups  = [ordered]@{}
foreach ($ext in $alwaysLFS) { $extGroups[$ext] = [System.Collections.Generic.List[string]]::new() }
$largeFiles = [System.Collections.Generic.List[string]]::new()

Get-ChildItem -LiteralPath $RepositoryRoot -File -Recurse -Force -ErrorAction SilentlyContinue |
    Where-Object {
        ($_.FullName.Split($sep) -notcontains '.git') -and
        ($_.Length -ge $FileSizeThreshold -or $_.Extension -cin $alwaysLFS)
    } |
    ForEach-Object {
        $rel   = $_.FullName.Substring($RepositoryRoot.Length).TrimStart($sep) -replace '\\', '/'
        $entry = if ($rel -match '\s') { '"{0}"' -f $rel } else { $rel }
        if ($_.Extension -cin $alwaysLFS) { $extGroups[$_.Extension].Add($entry) }
        else                              { $largeFiles.Add($entry) }
    }

$lines = @(
    '# Auto-Generated By "scripts/generate-git-attributes.ps1"'
    '# Re-Generate After Adding New Large Files'
    ''
    "# Generated: $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))"
    "# Threshold: $([math]::Round($FileSizeThreshold / 1MB, 0)) MB"
)

foreach ($ext in $alwaysLFS) {
    if ($extGroups[$ext].Count -eq 0) { continue }
    $lines += ''
    $lines += "# Files With Extension ""$ext"""
    $lines += ($extGroups[$ext] | Sort-Object | ForEach-Object { "$_ filter=lfs diff=lfs merge=lfs -text" })
}

if ($largeFiles.Count -gt 0) {
    $lines += ''
    $lines += "# Files At Or Above $([math]::Round($FileSizeThreshold / 1MB, 0)) MB"
    $lines += ($largeFiles | Sort-Object | ForEach-Object { "$_ filter=lfs diff=lfs merge=lfs -text" })
}

$content = ($lines -join "`n") + "`n"

[IO.File]::WriteAllText($attrFile, $content, [Text.UTF8Encoding]::new($false))

$total = $largeFiles.Count
foreach ($g in $extGroups.Values) { $total += $g.Count }
Write-Host ("{0} File(s) Flagged" -f $total)
Write-Host ("Wrote {0}" -f $attrFile)
